// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// Empty provides a mock function with no fields
func (_m *MockValidator) Empty() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Empty")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValidator_Empty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Empty'
type MockValidator_Empty_Call struct {
	*mock.Call
}

// Empty is a helper method to define mock.On call
func (_e *MockValidator_Expecter) Empty() *MockValidator_Empty_Call {
	return &MockValidator_Empty_Call{Call: _e.mock.On("Empty")}
}

func (_c *MockValidator_Empty_Call) Run(run func()) *MockValidator_Empty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValidator_Empty_Call) Return(_a0 bool) *MockValidator_Empty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Empty_Call) RunAndReturn(run func() bool) *MockValidator_Empty_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: presented
func (_m *MockValidator) Validate(presented string) bool {
	ret := _m.Called(presented)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(presented)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - presented string
func (_e *MockValidator_Expecter) Validate(presented interface{}) *MockValidator_Validate_Call {
	return &MockValidator_Validate_Call{Call: _e.mock.On("Validate", presented)}
}

func (_c *MockValidator_Validate_Call) Run(run func(presented string)) *MockValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockValidator_Validate_Call) Return(_a0 bool) *MockValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_Validate_Call) RunAndReturn(run func(string) bool) *MockValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
