#!/usr/bin/env bash
set -euo pipefail

# Refresh the vendored Scalar API Reference bundle for fully offline serving.
#
# Reads the pinned version from internal/api/static/scalar/VERSION, downloads
# the standalone JS + CSS, derives the web-font (.woff2) set referenced by the
# bundle and downloads those too, validates every byte against SHA256.expected
# (when present), rewrites the bundle so its font references point at the
# locally served path instead of fonts.scalar.com, and writes everything into
# internal/api/static/scalar/{scalar.js,scalar.css,fonts/*.woff2}.
#
# The SHA-256 baseline pins the *pristine* upstream downloads (the integrity
# anchor). The on-disk scalar.{js,css} are those pristine bytes with the font
# host rewritten to a local path — a deterministic transform, so re-running is
# byte-for-byte reproducible and produces no spurious git diff.

ASSET_DIR=$(dirname "$0")/../internal/api/static/scalar
ASSET_DIR=$(cd "$ASSET_DIR" && pwd)
VERSION_FILE="$ASSET_DIR/VERSION"
EXPECTED_FILE="$ASSET_DIR/SHA256.expected"
FONT_DIR="$ASSET_DIR/fonts"

# Scalar's standalone bundle hard-codes web-font URLs at this host; we rewrite
# them to a path served by the API so the docs UI makes zero external requests.
FONT_HOST="https://fonts.scalar.com"
LOCAL_FONT_PATH="/docs/assets/fonts"

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "FAIL: $VERSION_FILE missing"
  exit 1
fi

PIN=$(head -n1 "$VERSION_FILE" | tr -d '[:space:]')
echo "==> Refreshing Scalar bundle: $PIN"

if [[ -z "${SCALAR_MIRROR:-}" ]]; then
  SCALAR_MIRROR="https://cdn.jsdelivr.net/npm/${PIN}"
fi

JS_URL="$SCALAR_MIRROR/dist/browser/standalone.js"
# Styles ship as dist/style.css (not dist/browser/standalone.css).
CSS_URL="$SCALAR_MIRROR/dist/style.css"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT
mkdir -p "$TMP_DIR/fonts"

echo "    fetching $JS_URL"
curl -fsSL "$JS_URL" -o "$TMP_DIR/scalar.js"
echo "    fetching $CSS_URL"
curl -fsSL "$CSS_URL" -o "$TMP_DIR/scalar.css"

# Derive the web-font set straight from the bundle so a version bump that adds
# or drops a font is picked up automatically (bash 3.2-compatible: no mapfile).
FONT_URLS=()
while IFS= read -r url; do
  [[ -n "$url" ]] && FONT_URLS+=("$url")
done < <(grep -hoE "${FONT_HOST}/[A-Za-z0-9._-]+\.woff2" "$TMP_DIR/scalar.js" "$TMP_DIR/scalar.css" | sort -u)

echo "==> Fetching ${#FONT_URLS[@]} web fonts"
for url in "${FONT_URLS[@]}"; do
  name=$(basename "$url")
  echo "    fetching $url"
  curl -fsSL "$url" -o "$TMP_DIR/fonts/$name"
done

# Canonical relative file list (pristine downloads) — used for verify + regen.
files=(scalar.js scalar.css)
for url in "${FONT_URLS[@]}"; do files+=("fonts/$(basename "$url")"); done

if [[ -f "$EXPECTED_FILE" ]] && grep -q '[0-9a-f]\{64\}' "$EXPECTED_FILE"; then
  echo "==> Verifying SHA-256"
  while read -r expected file; do
    [[ -z "$expected" || "${expected:0:1}" == "#" ]] && continue
    if [[ ! -f "$TMP_DIR/$file" ]]; then
      echo "FAIL: $file listed in baseline but was not downloaded"
      exit 1
    fi
    got=$(shasum -a 256 "$TMP_DIR/$file" | awk '{print $1}')
    if [[ "$got" != "$expected" ]]; then
      echo "FAIL: $file SHA-256 mismatch. expected=$expected got=$got"
      exit 1
    fi
    echo "    OK $file"
  done <"$EXPECTED_FILE"
else
  echo "==> No SHA-256 baseline; recording fresh hashes into $EXPECTED_FILE"
  {
    echo "# Auto-generated by scripts/refresh-docs-ui.sh"
    for f in "${files[@]}"; do
      [[ -f "$TMP_DIR/$f" ]] || continue
      sum=$(shasum -a 256 "$TMP_DIR/$f" | awk '{print $1}')
      echo "$sum  $f"
    done
  } >"$EXPECTED_FILE"
fi

# Rewrite font references to the locally served path. Pristine bytes were
# already SHA-verified above; this transform is deterministic and reproducible.
sed -i.bak "s|${FONT_HOST}/|${LOCAL_FONT_PATH}/|g" "$TMP_DIR/scalar.js" "$TMP_DIR/scalar.css"
rm -f "$TMP_DIR/scalar.js.bak" "$TMP_DIR/scalar.css.bak"

# Offline guarantee: no external font URL may survive the rewrite.
if grep -qE "https?://[^\"')]+\.woff2" "$TMP_DIR/scalar.js" "$TMP_DIR/scalar.css"; then
  echo "FAIL: an external font URL survived the rewrite — offline guarantee broken:"
  grep -hoE "https?://[^\"')]+\.woff2" "$TMP_DIR/scalar.js" "$TMP_DIR/scalar.css" | sort -u | sed 's/^/  /'
  exit 1
fi

cp "$TMP_DIR/scalar.js" "$ASSET_DIR/scalar.js"
cp "$TMP_DIR/scalar.css" "$ASSET_DIR/scalar.css"
rm -rf "$FONT_DIR"
mkdir -p "$FONT_DIR"
cp "$TMP_DIR"/fonts/*.woff2 "$FONT_DIR/"

echo "==> Vendored Scalar bundle refreshed at $ASSET_DIR (${#FONT_URLS[@]} fonts, offline-ready)"
