#!/usr/bin/env bash
set -euo pipefail

# Refresh the vendored Scalar API Reference bundle.
#
# Reads the pinned version from internal/api/static/scalar/VERSION, downloads
# the corresponding standalone bundle, validates the SHA-256 against
# SHA256.expected (when present), and writes the bytes into
# internal/api/static/scalar/{scalar.js,scalar.css}.

ASSET_DIR=$(dirname "$0")/../internal/api/static/scalar
ASSET_DIR=$(cd "$ASSET_DIR" && pwd)
VERSION_FILE="$ASSET_DIR/VERSION"
EXPECTED_FILE="$ASSET_DIR/SHA256.expected"

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "FAIL: $VERSION_FILE missing"
  exit 1
fi

PIN=$(head -n1 "$VERSION_FILE" | tr -d '[:space:]')
echo "==> Refreshing Scalar bundle: $PIN"

if [[ -z "${SCALAR_MIRROR:-}" ]]; then
  SCALAR_MIRROR="https://cdn.jsdelivr.net/npm/${PIN}/dist/browser"
fi

JS_URL="$SCALAR_MIRROR/standalone.js"
CSS_URL="$SCALAR_MIRROR/standalone.css"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

echo "    fetching $JS_URL"
curl -fsSL "$JS_URL" -o "$TMP_DIR/scalar.js"
echo "    fetching $CSS_URL"
curl -fsSL "$CSS_URL" -o "$TMP_DIR/scalar.css" || echo "    (CSS optional; some Scalar versions ship JS only)"

if [[ -f "$EXPECTED_FILE" ]] && grep -q '[0-9a-f]\{64\}' "$EXPECTED_FILE"; then
  echo "==> Verifying SHA-256"
  while read -r expected file; do
    [[ -z "$expected" || "${expected:0:1}" == "#" ]] && continue
    if [[ ! -f "$TMP_DIR/$file" ]]; then continue; fi
    got=$(shasum -a 256 "$TMP_DIR/$file" | awk '{print $1}')
    if [[ "$got" != "$expected" ]]; then
      echo "FAIL: $file SHA-256 mismatch. expected=$expected got=$got"
      exit 1
    fi
    echo "    OK $file"
  done <"$EXPECTED_FILE"
else
  echo "==> No SHA-256 baseline; recording fresh hashes into $EXPECTED_FILE"
  {
    echo "# Auto-generated by scripts/refresh-docs-ui.sh"
    for f in scalar.js scalar.css; do
      [[ -f "$TMP_DIR/$f" ]] || continue
      sum=$(shasum -a 256 "$TMP_DIR/$f" | awk '{print $1}')
      echo "$sum  $f"
    done
  } >"$EXPECTED_FILE"
fi

cp "$TMP_DIR/scalar.js" "$ASSET_DIR/scalar.js"
[[ -f "$TMP_DIR/scalar.css" ]] && cp "$TMP_DIR/scalar.css" "$ASSET_DIR/scalar.css"

echo "==> Vendored Scalar bundle refreshed at $ASSET_DIR"
