// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/prometheus/common/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// Instant provides a mock function with given fields: ctx, name, query, ts
func (_m *MockQuerier) Instant(ctx context.Context, name string, query string, ts time.Time) (model.Vector, error) {
	ret := _m.Called(ctx, name, query, ts)

	if len(ret) == 0 {
		panic("no return value specified for Instant")
	}

	var r0 model.Vector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (model.Vector, error)); ok {
		return rf(ctx, name, query, ts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) model.Vector); ok {
		r0 = rf(ctx, name, query, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Vector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, name, query, ts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_Instant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instant'
type MockQuerier_Instant_Call struct {
	*mock.Call
}

// Instant is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - query string
//   - ts time.Time
func (_e *MockQuerier_Expecter) Instant(ctx interface{}, name interface{}, query interface{}, ts interface{}) *MockQuerier_Instant_Call {
	return &MockQuerier_Instant_Call{Call: _e.mock.On("Instant", ctx, name, query, ts)}
}

func (_c *MockQuerier_Instant_Call) Run(run func(ctx context.Context, name string, query string, ts time.Time)) *MockQuerier_Instant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockQuerier_Instant_Call) Return(_a0 model.Vector, _a1 error) *MockQuerier_Instant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_Instant_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (model.Vector, error)) *MockQuerier_Instant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
